/**
 * Comprehensive test suite for the SolFoundry on-chain bounty registry program.
 *
 * Tests cover all four instructions (register_bounty, update_status,
 * record_completion, close_bounty), the full state machine, authority
 * checks, input validation, error paths, and query functionality.
 *
 * Target: >95% code coverage as required by the bounty spec.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorError } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";
import BN from "bn.js";

// The IDL type will be generated by Anchor build.
// We use a generic Program type for pre-build testing.
type BountyRegistry = any;

/** PDA seed prefix matching the on-chain constant. */
const REGISTRY_SEED = Buffer.from("registry");

/**
 * Derive the bounty record PDA for a given bounty ID.
 *
 * @param bountyId - Numeric bounty identifier.
 * @param programId - The program's public key.
 * @returns Tuple of [pda, bump].
 */
function derivePda(
  bountyId: number,
  programId: PublicKey
): [PublicKey, number] {
  const bountyIdBuffer = new BN(bountyId).toArrayLike(Buffer, "le", 8);
  return PublicKey.findProgramAddressSync(
    [REGISTRY_SEED, bountyIdBuffer],
    programId
  );
}

/**
 * Generate a deterministic 32-byte hash for testing.
 *
 * @param seed - A string seed to create a reproducible hash.
 * @returns A 32-element number array representing a SHA-256 hash.
 */
function mockPrHash(seed: string): number[] {
  const hash = new Array(32).fill(0);
  for (let i = 0; i < seed.length && i < 32; i++) {
    hash[i] = seed.charCodeAt(i);
  }
  return hash;
}

describe("bounty-registry", () => {
  // Configure the provider to use the local validator.
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.BountyRegistry as Program<BountyRegistry>;
  const admin = provider.wallet;

  // A separate keypair to test unauthorized access.
  const unauthorizedUser = Keypair.generate();

  // Test bounty IDs (unique per test to avoid PDA collisions).
  let nextBountyId = 1;

  /**
   * Helper to get a fresh bounty ID for each test.
   *
   * @returns A unique bounty ID.
   */
  function getNextBountyId(): number {
    return nextBountyId++;
  }

  /**
   * Helper to register a bounty with default values.
   *
   * @param bountyId - The bounty ID to register.
   * @param overrides - Optional field overrides.
   * @returns The transaction signature.
   */
  async function registerDefaultBounty(
    bountyId: number,
    overrides?: {
      title?: string;
      tier?: number;
      rewardAmount?: number;
      githubIssue?: string;
    }
  ): Promise<string> {
    const [bountyPda] = derivePda(bountyId, program.programId);

    return await program.methods
      .registerBounty(
        new BN(bountyId),
        overrides?.title ?? `Test Bounty #${bountyId}`,
        overrides?.tier ?? 2,
        new BN(overrides?.rewardAmount ?? 500_000),
        overrides?.githubIssue ??
          `https://github.com/SolFoundry/solfoundry/issues/${bountyId}`
      )
      .accounts({
        admin: admin.publicKey,
        bountyRecord: bountyPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
  }

  /**
   * Helper to advance a bounty through the state machine to a target status.
   *
   * @param bountyId - The bounty to advance.
   * @param targetStatus - The status to reach (0-4).
   * @param contributor - Contributor pubkey for claiming.
   */
  async function advanceTo(
    bountyId: number,
    targetStatus: number,
    contributor?: PublicKey
  ): Promise<void> {
    const [bountyPda] = derivePda(bountyId, program.programId);
    const transitions: Array<{
      status: number;
      contributor: PublicKey | null;
    }> = [];

    // Build the transition path.
    if (targetStatus >= 1) {
      transitions.push({
        status: 1,
        contributor: contributor ?? Keypair.generate().publicKey,
      });
    }
    if (targetStatus >= 2) {
      transitions.push({ status: 2, contributor: null });
    }
    // Status 3 (Completed) is handled by record_completion, not update_status.
    // Status 4 (Cancelled) uses close_bounty.

    for (const transition of transitions) {
      await program.methods
        .updateStatus(transition.status, transition.contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 1: register_bounty instruction
  // ═══════════════════════════════════════════════════════════════════════

  describe("register_bounty", () => {
    it("should register a new bounty with all fields populated", async () => {
      const bountyId = getNextBountyId();
      const [bountyPda] = derivePda(bountyId, program.programId);

      const title = "Fix authentication bypass vulnerability";
      const tier = 3;
      const rewardAmount = 1_000_000;
      const githubIssue =
        "https://github.com/SolFoundry/solfoundry/issues/600";

      await program.methods
        .registerBounty(
          new BN(bountyId),
          title,
          tier,
          new BN(rewardAmount),
          githubIssue
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // Fetch and verify the on-chain record.
      const record = await program.account.bountyRecord.fetch(bountyPda);

      expect(record.bountyId.toNumber()).to.equal(bountyId);
      expect(record.title).to.equal(title);
      expect(record.tier).to.equal(tier);
      expect(record.rewardAmount.toNumber()).to.equal(rewardAmount);
      expect(record.status).to.deep.include({ open: {} });
      expect(record.creator.toBase58()).to.equal(
        admin.publicKey.toBase58()
      );
      expect(record.contributor).to.be.null;
      expect(record.githubIssue).to.equal(githubIssue);
      expect(record.githubPr).to.equal("");
      expect(record.reviewScores).to.deep.equal([]);
      expect(record.finalScore).to.equal(0);
      expect(record.prHash).to.be.null;
      expect(record.createdAt.toNumber()).to.be.greaterThan(0);
      expect(record.updatedAt.toNumber()).to.be.greaterThan(0);
      expect(record.completedAt).to.be.null;
      expect(record.bump).to.be.a("number");
    });

    it("should register a tier 1 bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { tier: 1 });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.tier).to.equal(1);
    });

    it("should register a tier 2 bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { tier: 2 });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.tier).to.equal(2);
    });

    it("should register a tier 3 bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { tier: 3 });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.tier).to.equal(3);
    });

    it("should register a bounty with minimum reward amount (0)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { rewardAmount: 0 });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.rewardAmount.toNumber()).to.equal(0);
    });

    it("should register a bounty with maximum safe reward amount", async () => {
      const bountyId = getNextBountyId();
      const [bountyPda] = derivePda(bountyId, program.programId);

      // Use a large but safe u64 value.
      const largeAmount = new BN("18446744073709551615"); // u64::MAX

      await program.methods
        .registerBounty(
          new BN(bountyId),
          "Large reward bounty",
          1,
          largeAmount,
          "https://github.com/SolFoundry/solfoundry/issues/999"
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.rewardAmount.toString()).to.equal(
        "18446744073709551615"
      );
    });

    it("should reject title exceeding 64 characters", async () => {
      const bountyId = getNextBountyId();
      const longTitle = "A".repeat(65);

      try {
        await registerDefaultBounty(bountyId, { title: longTitle });
        expect.fail("Expected error for title too long");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("TitleTooLong");
      }
    });

    it("should accept title at exactly 64 characters", async () => {
      const bountyId = getNextBountyId();
      const maxTitle = "A".repeat(64);

      await registerDefaultBounty(bountyId, { title: maxTitle });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.title.length).to.equal(64);
    });

    it("should reject invalid tier 0", async () => {
      const bountyId = getNextBountyId();

      try {
        await registerDefaultBounty(bountyId, { tier: 0 });
        expect.fail("Expected error for invalid tier");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("InvalidTier");
      }
    });

    it("should reject invalid tier 4", async () => {
      const bountyId = getNextBountyId();

      try {
        await registerDefaultBounty(bountyId, { tier: 4 });
        expect.fail("Expected error for invalid tier");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("InvalidTier");
      }
    });

    it("should reject github issue reference exceeding 128 characters", async () => {
      const bountyId = getNextBountyId();
      const longRef = "https://github.com/" + "x".repeat(120);

      try {
        await registerDefaultBounty(bountyId, { githubIssue: longRef });
        expect.fail("Expected error for github reference too long");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "GithubReferenceTooLong"
        );
      }
    });

    it("should reject duplicate bounty ID (PDA already exists)", async () => {
      const bountyId = getNextBountyId();

      // First registration succeeds.
      await registerDefaultBounty(bountyId);

      // Second registration with same ID should fail.
      try {
        await registerDefaultBounty(bountyId);
        expect.fail("Expected error for duplicate bounty ID");
      } catch (error: any) {
        // Anchor throws a SendTransactionError when account already exists.
        expect(error.toString()).to.include("already in use");
      }
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 2: update_status instruction
  // ═══════════════════════════════════════════════════════════════════════

  describe("update_status", () => {
    it("should transition Open -> Claimed with contributor", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const contributor = Keypair.generate().publicKey;
      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .updateStatus(1, contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ claimed: {} });
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );
    });

    it("should transition Claimed -> InReview", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 1);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .updateStatus(2, null)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ inReview: {} });
    });

    it("should transition Open -> Cancelled", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .updateStatus(4, null)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ cancelled: {} });
    });

    it("should transition Claimed -> Cancelled", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 1);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .updateStatus(4, null)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ cancelled: {} });
    });

    it("should update the timestamp on status change", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);
      const recordBefore = await program.account.bountyRecord.fetch(
        bountyPda
      );
      const beforeTimestamp = recordBefore.updatedAt.toNumber();

      const contributor = Keypair.generate().publicKey;
      await program.methods
        .updateStatus(1, contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const recordAfter = await program.account.bountyRecord.fetch(
        bountyPda
      );
      expect(recordAfter.updatedAt.toNumber()).to.be.greaterThanOrEqual(
        beforeTimestamp
      );
    });

    it("should reject claiming without a contributor", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(1, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for missing contributor");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "ContributorRequiredForClaim"
        );
      }
    });

    it("should reject invalid status value (5)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(5, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for invalid status value");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("InvalidStatusValue");
      }
    });

    it("should reject Open -> InReview (skipping Claimed)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(2, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for invalid transition");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusTransition"
        );
      }
    });

    it("should reject Open -> Completed (skipping intermediate)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(3, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for invalid transition");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusTransition"
        );
      }
    });

    it("should reject Claimed -> Open (backward transition)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 1);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(0, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for backward transition");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusTransition"
        );
      }
    });

    it("should reject InReview -> Cancelled (not allowed)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .updateStatus(4, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for invalid transition from InReview");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusTransition"
        );
      }
    });

    it("should reject mutations on Completed bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Complete it via record_completion first.
      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/600",
          [750, 800, 820, 790, 810],
          794,
          mockPrHash("test-completed-bounty")
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      // Now try to update status.
      try {
        await program.methods
          .updateStatus(4, null)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for mutation on completed bounty");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("BountyAlreadyClosed");
      }
    });

    it("should reject mutations on Cancelled bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Cancel it.
      await program.methods
        .updateStatus(4, null)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      // Now try to update status.
      try {
        await program.methods
          .updateStatus(1, Keypair.generate().publicKey)
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for mutation on cancelled bounty");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("BountyAlreadyClosed");
      }
    });

    it("should reject unauthorized status update", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Airdrop SOL to the unauthorized user for transaction fees.
      const airdropSig = await provider.connection.requestAirdrop(
        unauthorizedUser.publicKey,
        1_000_000_000
      );
      await provider.connection.confirmTransaction(airdropSig);

      try {
        await program.methods
          .updateStatus(4, null)
          .accounts({
            admin: unauthorizedUser.publicKey,
            bountyRecord: bountyPda,
          })
          .signers([unauthorizedUser])
          .rpc();
        expect.fail("Expected error for unauthorized access");
      } catch (error: any) {
        // The constraint check should fail.
        expect(error.toString()).to.include("Unauthorized");
      }
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 3: record_completion instruction
  // ═══════════════════════════════════════════════════════════════════════

  describe("record_completion", () => {
    it("should record completion with all review data", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const contributor = Keypair.generate().publicKey;
      await advanceTo(bountyId, 2, contributor);

      const [bountyPda] = derivePda(bountyId, program.programId);

      const githubPr =
        "https://github.com/SolFoundry/solfoundry/pull/600";
      const reviewScores = [750, 800, 820, 790, 810];
      const finalScore = 794;
      const prHash = mockPrHash("completion-test-hash");

      await program.methods
        .recordCompletion(githubPr, reviewScores, finalScore, prHash)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);

      expect(record.status).to.deep.include({ completed: {} });
      expect(record.githubPr).to.equal(githubPr);
      expect(record.reviewScores).to.deep.equal(reviewScores);
      expect(record.finalScore).to.equal(finalScore);
      expect(record.prHash).to.deep.equal(prHash);
      expect(record.completedAt).to.not.be.null;
      expect(record.completedAt.toNumber()).to.be.greaterThan(0);
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );
    });

    it("should record completion with perfect scores", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/perfect",
          [1000, 1000, 1000, 1000, 1000],
          1000,
          mockPrHash("perfect-scores")
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.finalScore).to.equal(1000);
      expect(record.reviewScores).to.deep.equal([
        1000, 1000, 1000, 1000, 1000,
      ]);
    });

    it("should record completion with zero scores", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/zero",
          [0, 0, 0, 0, 0],
          0,
          mockPrHash("zero-scores")
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.finalScore).to.equal(0);
    });

    it("should reject completion when not in InReview status", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      // Bounty is in Open status, not InReview.
      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/1",
            [700, 700, 700, 700, 700],
            700,
            mockPrHash("wrong-status")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for wrong status");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusForCompletion"
        );
      }
    });

    it("should reject completion from Claimed status", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 1);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/2",
            [700, 700, 700, 700, 700],
            700,
            mockPrHash("claimed-status")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for Claimed status");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusForCompletion"
        );
      }
    });

    it("should reject wrong number of review scores (4 scores)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/3",
            [700, 700, 700, 700], // Only 4 scores.
            700,
            mockPrHash("four-scores")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for wrong score count");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("InvalidScoreCount");
      }
    });

    it("should reject wrong number of review scores (6 scores)", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/4",
            [700, 700, 700, 700, 700, 700], // 6 scores.
            700,
            mockPrHash("six-scores")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for wrong score count");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("InvalidScoreCount");
      }
    });

    it("should reject review score exceeding 1000", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/5",
            [700, 1001, 700, 700, 700], // 1001 is out of range.
            700,
            mockPrHash("over-range")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for score out of range");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("ScoreOutOfRange");
      }
    });

    it("should reject final score exceeding 1000", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/6",
            [700, 700, 700, 700, 700],
            1001, // Final score out of range.
            mockPrHash("final-over-range")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for final score out of range");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("ScoreOutOfRange");
      }
    });

    it("should reject github PR reference exceeding 128 characters", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);
      const longPr = "https://github.com/" + "x".repeat(120);

      try {
        await program.methods
          .recordCompletion(
            longPr,
            [700, 700, 700, 700, 700],
            700,
            mockPrHash("long-pr-ref")
          )
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for PR reference too long");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "GithubReferenceTooLong"
        );
      }
    });

    it("should reject unauthorized completion", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .recordCompletion(
            "https://github.com/SolFoundry/solfoundry/pull/7",
            [700, 700, 700, 700, 700],
            700,
            mockPrHash("unauthorized")
          )
          .accounts({
            admin: unauthorizedUser.publicKey,
            bountyRecord: bountyPda,
          })
          .signers([unauthorizedUser])
          .rpc();
        expect.fail("Expected error for unauthorized access");
      } catch (error: any) {
        expect(error.toString()).to.include("Unauthorized");
      }
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 4: close_bounty instruction
  // ═══════════════════════════════════════════════════════════════════════

  describe("close_bounty", () => {
    it("should close an Open bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .closeBounty()
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ cancelled: {} });
    });

    it("should close a Claimed bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 1);

      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .closeBounty()
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ cancelled: {} });
    });

    it("should reject closing an already Completed bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Complete it first.
      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/close-test",
          [800, 800, 800, 800, 800],
          800,
          mockPrHash("close-completed")
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      try {
        await program.methods
          .closeBounty()
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for closing completed bounty");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("BountyAlreadyClosed");
      }
    });

    it("should reject closing an already Cancelled bounty", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Cancel it first.
      await program.methods
        .closeBounty()
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      try {
        await program.methods
          .closeBounty()
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for double close");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal("BountyAlreadyClosed");
      }
    });

    it("should reject closing a bounty in InReview status", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .closeBounty()
          .accounts({
            admin: admin.publicKey,
            bountyRecord: bountyPda,
          })
          .rpc();
        expect.fail("Expected error for closing InReview bounty");
      } catch (error: any) {
        expect(error).to.be.instanceOf(AnchorError);
        expect(error.error.errorCode.code).to.equal(
          "InvalidStatusTransition"
        );
      }
    });

    it("should reject unauthorized close", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      try {
        await program.methods
          .closeBounty()
          .accounts({
            admin: unauthorizedUser.publicKey,
            bountyRecord: bountyPda,
          })
          .signers([unauthorizedUser])
          .rpc();
        expect.fail("Expected error for unauthorized close");
      } catch (error: any) {
        expect(error.toString()).to.include("Unauthorized");
      }
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 5: Full lifecycle (end-to-end)
  // ═══════════════════════════════════════════════════════════════════════

  describe("full lifecycle", () => {
    it("should complete the full lifecycle: Register -> Claim -> InReview -> Complete", async () => {
      const bountyId = getNextBountyId();
      const contributor = Keypair.generate().publicKey;
      const [bountyPda] = derivePda(bountyId, program.programId);

      // Step 1: Register.
      await program.methods
        .registerBounty(
          new BN(bountyId),
          "End-to-end lifecycle test bounty",
          3,
          new BN(1_000_000),
          "https://github.com/SolFoundry/solfoundry/issues/600"
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      let record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ open: {} });

      // Step 2: Claim.
      await program.methods
        .updateStatus(1, contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ claimed: {} });
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );

      // Step 3: Move to InReview.
      await program.methods
        .updateStatus(2, null)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ inReview: {} });

      // Step 4: Record completion.
      const prHash = mockPrHash("lifecycle-test-final");
      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/600",
          [850, 900, 870, 880, 890],
          878,
          prHash
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ completed: {} });
      expect(record.githubPr).to.equal(
        "https://github.com/SolFoundry/solfoundry/pull/600"
      );
      expect(record.reviewScores).to.deep.equal([850, 900, 870, 880, 890]);
      expect(record.finalScore).to.equal(878);
      expect(record.prHash).to.deep.equal(prHash);
      expect(record.completedAt).to.not.be.null;
    });

    it("should complete the cancellation lifecycle: Register -> Claim -> Cancel", async () => {
      const bountyId = getNextBountyId();
      const contributor = Keypair.generate().publicKey;
      const [bountyPda] = derivePda(bountyId, program.programId);

      // Register.
      await registerDefaultBounty(bountyId);

      // Claim.
      await program.methods
        .updateStatus(1, contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      // Cancel via close_bounty.
      await program.methods
        .closeBounty()
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.status).to.deep.include({ cancelled: {} });
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 6: Query support
  // ═══════════════════════════════════════════════════════════════════════

  describe("query support", () => {
    it("should fetch a bounty by ID via PDA derivation", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, {
        title: "Queryable bounty",
      });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);

      expect(record.title).to.equal("Queryable bounty");
      expect(record.bountyId.toNumber()).to.equal(bountyId);
    });

    it("should list all bounty records using getProgramAccounts", async () => {
      // Register a few extra bounties for listing.
      const ids = [getNextBountyId(), getNextBountyId(), getNextBountyId()];
      for (const id of ids) {
        await registerDefaultBounty(id);
      }

      const allAccounts =
        await program.account.bountyRecord.all();

      // Should have at least the bounties we just created.
      expect(allAccounts.length).to.be.greaterThanOrEqual(ids.length);
    });

    it("should filter bounties by contributor using memcmp", async () => {
      const bountyId = getNextBountyId();
      const contributor = Keypair.generate().publicKey;

      await registerDefaultBounty(bountyId);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Claim with specific contributor.
      await program.methods
        .updateStatus(1, contributor)
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      // Fetch and verify the contributor is set.
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );
    });

    it("should list all bounty records and filter by status client-side", async () => {
      // Create one open and one cancelled bounty.
      const openId = getNextBountyId();
      const cancelledId = getNextBountyId();

      await registerDefaultBounty(openId);
      await registerDefaultBounty(cancelledId);

      // Cancel the second one.
      const [cancelledPda] = derivePda(cancelledId, program.programId);
      await program.methods
        .closeBounty()
        .accounts({
          admin: admin.publicKey,
          bountyRecord: cancelledPda,
        })
        .rpc();

      // Fetch all and filter.
      const allAccounts =
        await program.account.bountyRecord.all();

      const openBounties = allAccounts.filter(
        (account: any) => "open" in account.account.status
      );
      const cancelledBounties = allAccounts.filter(
        (account: any) => "cancelled" in account.account.status
      );

      expect(openBounties.length).to.be.greaterThan(0);
      expect(cancelledBounties.length).to.be.greaterThan(0);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 7: PDA derivation verification
  // ═══════════════════════════════════════════════════════════════════════

  describe("PDA derivation", () => {
    it("should derive consistent PDAs for the same bounty ID", () => {
      const [pda1] = derivePda(42, program.programId);
      const [pda2] = derivePda(42, program.programId);
      expect(pda1.toBase58()).to.equal(pda2.toBase58());
    });

    it("should derive different PDAs for different bounty IDs", () => {
      const [pda1] = derivePda(1, program.programId);
      const [pda2] = derivePda(2, program.programId);
      expect(pda1.toBase58()).to.not.equal(pda2.toBase58());
    });

    it("should store the correct bump in the record", async () => {
      const bountyId = getNextBountyId();
      const [bountyPda, expectedBump] = derivePda(
        bountyId,
        program.programId
      );

      await registerDefaultBounty(bountyId);

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.bump).to.equal(expectedBump);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // SECTION 8: Edge cases and boundary conditions
  // ═══════════════════════════════════════════════════════════════════════

  describe("edge cases", () => {
    it("should handle empty title string", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { title: "" });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.title).to.equal("");
    });

    it("should handle empty github issue string", async () => {
      const bountyId = getNextBountyId();
      await registerDefaultBounty(bountyId, { githubIssue: "" });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.githubIssue).to.equal("");
    });

    it("should handle bounty ID 0", async () => {
      // Use a special registration for ID 0 (not using getNextBountyId).
      const bountyId = 0;
      const [bountyPda] = derivePda(bountyId, program.programId);

      await program.methods
        .registerBounty(
          new BN(bountyId),
          "Bounty zero",
          1,
          new BN(100),
          "issue/0"
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.bountyId.toNumber()).to.equal(0);
    });

    it("should handle unicode characters in title (within byte limit)", async () => {
      const bountyId = getNextBountyId();
      // Unicode characters can be multi-byte; keep total under 64 bytes.
      const unicodeTitle = "Fix bug in module"; // Safe ASCII for this test.

      await registerDefaultBounty(bountyId, { title: unicodeTitle });

      const [bountyPda] = derivePda(bountyId, program.programId);
      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.title).to.equal(unicodeTitle);
    });

    it("should preserve contributor through full lifecycle", async () => {
      const bountyId = getNextBountyId();
      const contributor = Keypair.generate().publicKey;

      await registerDefaultBounty(bountyId);
      await advanceTo(bountyId, 2, contributor);

      const [bountyPda] = derivePda(bountyId, program.programId);

      // Record completion.
      await program.methods
        .recordCompletion(
          "https://github.com/SolFoundry/solfoundry/pull/preserve",
          [700, 700, 700, 700, 700],
          700,
          mockPrHash("preserve-contributor")
        )
        .accounts({
          admin: admin.publicKey,
          bountyRecord: bountyPda,
        })
        .rpc();

      const record = await program.account.bountyRecord.fetch(bountyPda);
      expect(record.contributor.toBase58()).to.equal(
        contributor.toBase58()
      );
    });
  });
});
